### ISSUE TITLE
Pip installation problem with Python 3.8

### ISSUE THREAD

**Issue by marek-statsperform** [endrebak/kerneltree#1]
When I am running `pip install kerneltree` with python3.8, I get the following error:
```bash
    Compiling src/kerneltree.pyx because it depends on /usr/local/lib/python3.8/dist-packages/Cython/Includes/libc/string.pxd.
      [1/1] Cythonizing src/kerneltree.pyx
      /usr/local/lib/python3.8/dist-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-5pl17unq/kerneltree_1c6e885edfea41c7b8a8fc9a345f5666/src/kerneltree.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      warning: src/kerneltree.pyx:15:31: Not all members given for struct 'rb_root'
      warning: src/kerneltree.pyx:15:31: Not all members given for struct 'rb_root'
      running egg_info
      creating /tmp/pip-pip-egg-info-_1cl6snh/kerneltree.egg-info
      writing /tmp/pip-pip-egg-info-_1cl6snh/kerneltree.egg-info/PKG-INFO
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5pl17unq/kerneltree_1c6e885edfea41c7b8a8fc9a345f5666/setup.py", line 11, in <module>
          setup(
        File "/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 300, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "/usr/local/lib/python3.8/dist-packages/setuptools/command/egg_info.py", line 664, in write_pkg_info
          metadata.write_pkg_info(cmd.egg_info)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 1141, in write_pkg_info
          self.write_pkg_file(pkg_info)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 197, in write_pkg_file
          write_field('License', rfc822_escape(license))
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/util.py", line 517, in rfc822_escape
          lines = header.split('\n')
      AttributeError: 'list' object has no attribute 'split'
```

**Comment by endrebak** [comment]
Is there any reason you aren't using my NCLS library? :D

**Comment by marek-statsperform** [comment]
Well, there is not. I am using it now.
